### ISSUE TITLE
Error codes from CoreMidi getting object properties

### ISSUE THREAD

**Issue by BradleyRoss** [DerekCook/CoreMidi4J#23]
I was going through some topics on CoreMidi and the JNI interface and noticed that CoreMidiDeviceProvider is not examining the return codes when using MIDIObjectGetIntegerProperty and MIDIObjectGetStringProperty.  See CoreMidiSample1.txt.

I was having some problems understanding the Apple Documentation, but if it is like other systems that I have encountered, the property value returned is not meaningful (undefined) unless the return code is zero.  When I check the return codes (see attached source code), a lot of the zeroes and NULL values returned as property values become "undefined".  This code also lists the entirety of the CFDictionary objects returned by MIDIObjectGetProperties.  It appears that attempts to get properties not in the CFDictionary object will return an error code.

The results of running the program on my workstation are found in CoreMidiSample1Listing.txt attached below

By the way the C code below can be found at [https://github.com/BradleyRoss/ObjectiveC-Examples](https://github.com/BradleyRoss/ObjectiveC-Examples)

[CoreMidiSample1.txt](https://github.com/DerekCook/CoreMidi4J/files/1318968/CoreMidiSample1.txt)

[CoreMidiSample1Listing.txt](https://github.com/DerekCook/CoreMidi4J/files/1319007/CoreMidiSample1Listing.txt)

**Comment by DerekCook** [comment]
Whilst I would not disagree with what you are saying that we could be checking return values, I am not certain why you are raising this as an issue?

Are you having specific problems in your environment because of some failure to check return values, or are you just being critical of somebody else's code?

No problem with objective criticism, of course, but I need to understand priority (I am not sitting about with nothing to do, waiting like a coiled spring to fix non issues ;-) ). If this is causing a failure in your environment, then it has a higher priority than if there are no problems in the results.

The question then is what value would checking the return values give us, for example, over and above the current checks for null pointers when querying names. If it adds no further value, then there is little point in adding more code. I can see some benefit maybe for the numeric values. 

I do not see this as a high priority, so if you want to take a branch of the code and program an improvement for us to consider a merge, then be my guest.

**Comment by DerekCook** [comment]
Closed as no reply to response. You can always raise an issue with specific details as to why this is a problem
