### ISSUE TITLE
Is there an example project?

### ISSUE THREAD

**Issue by cansik** [DerekCook/CoreMidi4J#24]
It's a bit hard to guess how to use your library. The readme is not showing a real example on how to use the library, for example to send sysex messages.

Would be nice to have short code examples for some use cases.

**Comment by brunchboy** [comment]
I’m sorry this wasn’t evident, but in general there is no need to use the library directly. You simply make sure it is on the class path, and then ensure you choose the version of the MIDI device provided by this library instead of the one provided by the normal Java implementation, and this allows your MIDI operations to work correctly.

In other words, you send a sysex message the way you always send a sysex message in Java, following the normal Java MIDI documentation. But if you send it to the version of the device provided by CoreMIDI4J, it actually works.

Does that help?

**Comment by brunchboy** [comment]
This is explained in the [Using CoreMidi4J](https://github.com/DerekCook/CoreMidi4J#using-coremidi4j) section of the project README. There is also example code showing how to do more complex things which do involve directly accessing the library.

**Comment by DerekCook** [comment]
Hi,

James is spot on, so, after following the guidance referred to above,  it should be as simple as looking up general examples on the internet for Java MIDI. Follow the section that James refers to above if you wish to use specific CoreMIDI4J features such as filtering out broken devices and adding listeners to detect MIDI devices being added or removed. 

I think the only thing I would add on SYSEX compared to general MIDI is, depending on you MIDI interface (and the size of its data buffers) and size of the SYSEX messages you are dealing with, is that you may need to break down large messages into smaller chunks and send the messages bit by bit with a small delay between each send.

If you see no good exampled for doing that, then let me know and I will dig out an example when I get time.

**Comment by brunchboy** [comment]
@cansik Were you able to do what you need? Can we close this issue?

**Comment by cansik** [comment]
@brunchboy Yes you can close the issue :) Thank you for your help.

**Comment by bbulkow** [comment]
I have come to this recently, and given how easy it should be to use, I think a single working example of iterating and ignoring and sending SysEx would be wonderful. 

There are a number of questions I have on reading the README that would be answered by an example. So am I supposed to "directly" use the uk.co.xfactorylibrarians.coremidi4j.getWorkingDeviceInfo() ? It looks like you've massaged the names - can I rely on this? All of these things I will have to experiment with.

The example code also depends on a class called "Example" which isn't included.

I'm not saying any of this is hard, it is that it'll take an hour or two when an example would tell the tale perfectly.

**Comment by DerekCook** [comment]
Hi,

As James mentions above we have [example code](https://github.com/DerekCook/CoreMidi4J#using-coremidi4j), not an example project.  Yes, we could have one, but with the simplicity of the interface and the clearly documented examples, it never felt warranted. From the Example page, all you need to do is copy and paste the sample code into your own project and experiment. It's as simple as that.

At its simplest level, described under **Using CoreMidi4J**, just include CoreMIDI4J.jar in your build path and you do not need to do anything, and external MIDI comms will work. But you will also get the broken devices still listed, and your program will not be able to earn about changes to the MIDI environment. To get those features, your program then needs to be aware of CoreMIDI4J as a class, and check that it exists to use its features

So the _Available_ class example shows the next steps of **Checking CoreMidi4J's availability** and the _Example_ class example then shows you how to register a notification listener for Environment changes.

Finally **Filtering Out Broken MIDI Devices** shows you how to get rid of the broken devices.

**Comment by DerekCook** [comment]
Hi,

I am not certain what you mean by 

> iterating and ignoring and sending SysEx

Can you please elaborate?

As James mentions above, we have [example code](https://github.com/DerekCook/CoreMidi4J#using-coremidi4j), not an example project.  Yes, we could have one, but with the simplicity of the interface and the clearly documented examples, it never felt warranted. From the Example page, all you need to do is copy and paste the sample code into your own project and experiment. It's as simple as that.

At its simplest level, described under **Using CoreMidi4J**, just include CoreMIDI4J.jar in your build path and you do not need to do anything else, and external MIDI comms will work. 

But you will also still get the broken devices listed when you use the standard Java MIDI function `getMidiDeviceInfo()` to query devices, and your program will not be able to learn about changes to the MIDI environment. To get those features, your program then needs to be aware of CoreMIDI4J as a class, and check that it exists to use its features

So the _Available_ class example shows the next steps of **Checking CoreMidi4J's availability** and the _Example_ class example then shows you how to register a notification listener for Environment changes.

Finally **Filtering Out Broken MIDI Devices** shows you how to get rid of the broken devices by calling the CoreMIDI4J `getMidiDeviceInfo()` function.

**Comment by brunchboy** [comment]
Hello, @bbulkow, thanks for writing. As Derek says, you don’t need to do anything to use CoreMidi4J other than put it in your class path, and the underlying Java MIDI system will activate it and make its versions of the MIDI devices attached to your computer available to Java. The only times you need to interact with any of our classes directly are if you are building software that you are shipping to other people, and you want to help make sure your users choose only the versions of MIDI devices that CoreMidi4J offers, and not the broken ones that Java itself offers on the Mac. If so, you can use code like that shown in our examples to filter out the devices CoreMidi4J provides when you are presenting a list of devices for your users to choose.

If you want to try these examples, as Derek suggested, copy and paste them into files named `Available.java` and `Example.java`, and then run `javac` on them, and then `java` with the resulting class files and CoreMidi4J on the class path.

I am also curious what you meant by “iterating and ignoring and sending SysEx.” We do not attempt to document how to use the Java MIDI API because we don’t change how you do that; simply use the existing API in the normal way. The advantage CoreMidi4J gives you is that on the Mac there will be an additional set of devices available to you, whose names begin with `CoreMidi4J - `, and if you use these devices instead of the ones whose names do not begin that way, then your code which tries to send SysEx messages will actually work.

Then if you want to get fancier and have your user interface update itself to respond to changes in the MIDI environment (someone plugging in or disconnecting a synthesizer or controller), you can follow the later examples Derek mentioned.

**Comment by bbulkow** [comment]
Let me open another issue. Simply having CoreMidi4j isn't working exactly the same as the same code running on windows without providers.

**Comment by brunchboy** [comment]
Ok, we look forward to more details. I am guessing your code is not trying to work with the CoreMidi4J-provided version of the device you are trying to talk to, but you may have also run into some other Mac MIDI issue which we have not (yet?) tried to fix. And it would be worth verifying that CoreMidi4J loaded successfully, as the examples show how to do.
