### ISSUE TITLE
SysEx Messages not work on macOS

### ISSUE THREAD

**Issue by Tobisaninfo** [DerekCook/CoreMidi4J#28]
Hi,
I tried out you midi library on macOS in hope of an improvement of reading SysEx messages from a physical midi device, because of an implementation error in the java midi implementation. But unfortunately your implementation produces the same error. Do you have any idea, how I could deal with it?

Thanks for help
Tobias

**Comment by brunchboy** [comment]
Without more details, no. What error?

**Comment by brunchboy** [comment]
Also, how have you set things up to use our library? It is also possible that you have simply not set it up to be loaded correctly. We use it to work with SysEx messages from physical devices in both directions with no problems.

**Comment by Tobisaninfo** [comment]
Oh sorry, thats my fault. 

In my tests I use a simple midi device with a slider on it, that sends SysEx messages by changing its position. On java macOS (10.14) side using normal midi implementation or CoreMIDI4J the midi SysEx messages looks linke this:

```
[-9, 0, 0, 0, 0, 0, 0]
[-9, 0, 0, 0, 0, 0, 0]
[-9, 0, 0, 0, 0, 0, 0]
[-9, 0, 0, 0, 0, 0, 0]
[-9, 0, 0, 0, 0, 0, 0]
```

On windows (windows 10) and using CoreMIDI on Objective-C directly the same messages looks linke this:

 ```
 [-16, 127, 127, 4, 1, 0, 121, -9]
 [-16, 127, 127, 4, 1, 0, 120, -9]
 [-16, 127, 127, 4, 1, 0, 119, -9]
 [-16, 127, 127, 4, 1, 0, 118, -9]
 [-16, 127, 127, 4, 1, 0, 117, -9]
 [-16, 127, 127, 4, 1, 0, 116, -9]
 [-16, 127, 127, 4, 1, 0, 115, -9]
 [-16, 127, 127, 4, 1, 0, 114, -9]
 [-16, 127, 127, 4, 1, 0, 113, -9] 
```

The interesting  number of the SysEx message is the 7th number.

To use midi in java, I'll use the following code snippet (in the real project it is more complex):

```java
CoreMidiDeviceProvider.isLibraryLoaded();

...

MidiDevice inputDevice = MidiSystem.getMidiDevice(input);

Transmitter trans = inputDevice.getTransmitter();
trans.setReceiver(this);
inputDevice.open();

...

@Override
public void send(MidiMessage message, long timeStamp)
{
	System.out.println(Arrays.toString(message.getMessage()));
}
```

If I can help you in any way, please let me know.

**Comment by Tobisaninfo** [comment]
My midi device is called „PD 12“. Should I use the „CoreMIDI4J - PD12“ device instead of „PD12“. Could this fix my issue?

**Comment by brunchboy** [comment]
Yes, that is exactly what I was going to suggest. You need to use the devices provided by CoreMIDI4J, not the ones provided by the standard Java MIDI system. If you use our `CoreMidiDeviceProvider` instead of the standard `MidiSystem` to enumerate devices as suggested in the [readme](
https://github.com/DerekCook/CoreMidi4J#filtering-out-broken-midi-devices) you will be protected from this kind of problem, because it only returns the devices that work properly.

**Comment by Tobisaninfo** [comment]
That does work great now. Now it's harder to set the MIDI device by name in code for both platforms, windows and macOS. But thats my problem.

Thanks for help.

**Comment by brunchboy** [comment]
It is not hard, actually! Please read the whole readme more carefully. You can use our library on Windows as well, and in that case when you ask `CoreMidiDeviceProvider` for the list of working MIDI devices, it will give you the standard Java ones, which work there.

**Comment by Tobisaninfo** [comment]
The problem is not the `CoreMidiDeviceProvider`that problem could I fix in an easy way. Actually I'll tried to implement CoreMIDI for java myself. But I canceled it, after I found your library. The actually problem is the naming prefix for the device itself.

**Comment by brunchboy** [comment]
Device names are different across platforms, even without CoreMidi4J, I have found, which is why my programs always either let the user choose the device (after filtering out the broken ones) and store that name for future use, or use regular expressions to match the variations I saw across Windows, MacOS, and Linux.

Thanks for letting us know you were able to get past this issue, though, and best of luck in your projects!

**Comment by DerekCook** [comment]
Hi, I missed this due to time zone differences and then a hectic day! I am glad you have it resolved. As ever James has given sterling advice, and I agree with James it is best not to hard code the device names for the reasons given

We prefix the Core MIDI device names so that they are unique in an unfiltered list using the standard MIDI APIs for getting device info, otherwise that would be very confusing. 

But I have wondered now and again if we could actually strip the prefix when you are requesting the names via the CoreMIDI4J API, as at that point we have filtered out the broken devices on OS X (or just using the standard API on WIndoze).

**Comment by brunchboy** [comment]
Thanks for the kind words, Derek. And I was wondering the same thing, about potentially returning the base names when people are explicitly getting devices through our API. That might be nice, but I didn’t take the time to look at how clean it might be to implement.

**Comment by DerekCook** [comment]
Hi, James
      
      I wouldn't have thought it would be too hard, even if you looked
      at it on the Java side and simply looked the for prefix string and
      stripped it off there.
      
      I might have a look at it some time. Of course it changes the
      names again when you next do a software release, which might be
      confusing to users. 
      
      But I have been wondering about it. I guess if we both vote for
      it, then we do it!
      
      Still been too busy in work to look at that Java 10 in Windoze
      Port name bug. Maybe in the next few weeks.....
      
      Cheers
      Derek

**Comment by brunchboy** [comment]
We could add a new method which gives you the un-prefixed names, leaving the old one unchanged (perhaps marked as deprecated), and then software could adopt the new method when its developers want the names to change, and not before.
