### ISSUE TITLE
Split Sysex messages are not handled properly

### ISSUE THREAD

**Issue by eclab** [DerekCook/CoreMidi4J#37]
Java has a mechanism for sending sysex messages piecemeal:

https://docs.oracle.com/javase/7/docs/api/javax/sound/midi/SysexMessage.html

In short: if you want to send a sysex message as several SysexMessage objects (as a stream essentially), possibly separated by a pause in time, then the FIRST SysexMessage has a status of 0xF0, and every SUBSEQUENT SysexMessage has a (java-special) "status" of 0xF7.  The FINAL SysexMessage is the only one which is terminated with 0xF7.  Here's an example of some messages demonstrating the scenario

    SysexMessage[] foo = new SysexMessage[]
        {
        new SysexMessage(new byte[] { (byte)0xF0, 0x01, 0x02, 0x03, 0x04 }, 5),
        new SysexMessage(new byte[] { (byte)0xF7, 0x05, 0x06, 0x07, 0x08 }, 5),
        new SysexMessage(new byte[] { (byte)0xF7, 0x09, 0x0A, 0x0B, 0x0C }, 5),
        new SysexMessage(new byte[] { (byte)0xF7, 0x0D, 0x0E, 0x0F, (byte)0xF7 }, 5),
        };

You'd then send these messages.

EXPECTED RESULT on MIDIMonitor:

One single Sysex Message of the form

0xF0 0x01 0x02 0x03 0x04 .... 0x0D, 0x0E, 0x0F, 0xF7

ACTUAL RESULT on MIDI Monitor:

Sysex Message:  0xF0 0x01 0x02 0x03 0x04 0xF7
Invalid Message: 0x05, 0x06, 0x07, 0x08
Invalid Message: 0xF7, 0x09, 0x0A, 0x0B, 0x0C
Invalid Message: 0xF7, 0x0D, 0x0E, 0x0F, 0xF7

Not good.

MY GUESS: It looks like CoreMidi4Java is treating the 0xF7 of each subsequent message as actual data, rather than a "fake" status byte, and actually sending it on.  It should be stripping out the initial 0xF7 from each such continuing Sysex Messge.

**Comment by brunchboy** [comment]
Thank you for reporting this. I’m eager to hear what Derek feels, since this is his project, but I can think of some ways to deal with this, although I can’t imagine why anyone would ever want to split up a sysex message into multiple objects like that. What purpose does it serve? It’s not as though you can save any memory that way, because the MIDI system would have to buffer them until the last one was received anyway.

Also, is there some sort of timeout? What if hours go by without ever receiving the object with the concluding `0xF7`?

I can see how we could return error codes and discard the buffered `SysexMessage` objects if we were buffering up a series of incomplete ones and someone tried to send one that did not begin with `0xF7`, but… one thing that strikes me very strongly is that whoever created this API was _not_ thinking about the fact that Java is multi-threaded. If multiple threads are sending sysex messages at the same time, this API is inherently unsafe and nondeterministic, unless we keep separate thread-local buffers for partial messages.

And again, why? What value does this complexity serve? We might better off simply always throwing an exception if you try to send a `SysexMessage` that is incomplete.

**Comment by brunchboy** [comment]
(Also, your example seems to be missing the code which actually tries to send the array of `SysexMessage` objects. Does it just loop over them calling `send()`?)

**Comment by DerekCook** [comment]
Hi,

Apologies for not replying sooner. Work has been manic, and James's response reminded me that I have not replied.

I have seen this behaviour on Java MIDI in reverse, so am I used to handling it on incoming messages on some interfaces, but never have used it on outgoing messages. I can only assume it is a legacy feature to support sending of large sysex messages over interfaces where the data buffers are smaller. I.e. you have a message that 10,000 bytes to send, but your interface only have buffers of 1,000 bytes, then you need to split the message up that fits within some intermediate buffer and then you allow a small delay before sending the next to allow the receiving device time to process the message

I do this in my own librarian software as I had this problem when I switched to a MOTU MIDEXPRESS 128 in 2006 which possibly has small buffers as a multi-port device, and I found that sending large messages in one go would not get received correctly. However, I simply chunk the message up, send each chunk with a delay in between each send. I do not add the F7 at the start of a buffer as you describe, and this all goes fine via CoreMIDI4J.

So I guess the first question is to just understand why this behaviour would still be useful in this day and age, and how essential do you need it? Can you just chunk a message up like how I describe, which I know works. I.e. divide the message up but do not add the F7s at the start of a buffer.

**Comment by eclab** [comment]
> On Sep 23, 2020, at 4:27 PM, James Elliott <notifications@github.com> wrote:
> 
> Thank you for reporting this. I’m eager to hear what Derek feels, since this is his project, but I can think of some ways to deal with this, although I can’t imagine why anyone would ever want to split up a sysex message into multiple objects like that.

It is *very* common.  A great many earlier ('80s, '90s) MIDI synthesizers have small buffers and cannot receive their own patch or bulk dump sysex all at once: they require that pauses be placed in-between chunks of data.  In fact this is often stipulated in their sysex docs explicitly. Ones that come to mind immediately: D10 and D110 (and probably other Roland D series like the D50), Casio CZ series, Kawai K5, Yamaha TG-33, Yamaha SY-22 and SY-35, Yamaha FB-01, and so on.  Indeed the CZ series relies a complex protocol of such message streams.

If you can't break a SysexMessage into pieces, and manually send them spaced by (say) 100ms, there's no way to send a message to these machines without inundating them with one big message.  That's the purpose of this Java feature.


> Also, is there some sort of timeout? What if hours go by without ever receiving the object with the concluding 0xF7?

I guess it'd depend on the receiving machine.  The MIDI spec says nothing about how long a message should take to arrive regardless of the type.  It does say this about sysex however:

"To avoid hanging a system, a transmitter should send a status byte immediately after the end of an Exclusive transmission so the receiver can return to normal operation.  Although any Status Byte (except Real-Time) will end an exclusive message, an EOX should always be sent at the end of a System Exclusive message.  Real time messages may be inserted between data bytes of an Exclusive message in order to maintain synchronization, and can not be used to terminate an exclusive message."

So:
	- There's no timeout on sysex messages or rules regarding their speed of transmission, but an 0xF7 ought to show up as soon as possible after the data is finished.
	- If (say) a NOTE ON arrives, the sysex is terminated, so there's no worry about hanging.
	- If (say) a CLOCK arrives, it may freely be processed in the middle of the sysex message.


> I can see how we could return error codes and discard the buffered SysexMessage objects if we were buffering up a series of incomplete ones and someone tried to send one that did not begin with 0xF7, but… one thing that strikes me very strongly is that whoever created this API was not thinking about the fact that Java is multi-threaded. If multiple threads are sending sysex messages at the same time, this API is inherently unsafe and nondeterministic, unless we keep separate thread-local buffers for partial messages.

That's no doubt true.  But while it's a brittle abstraction, its a formal part of the Java MIDI spec and should be handled at the app level.


> And again, why? What value does this complexity serve? We might better off simply always throwing an exception if you try to send a SysexMessage that is incomplete.

So my answer to you would be:

1. That'd make CoreMIDI4J is in violation of the Java spec
2. It'd make sending valid sysex to a number of older machines difficult or impossible on the Mac

As you may recall, I maintain Edisyn, a large patch editor library.  Without this properly implemented, I have to rely on ugly and invalid hacks to send data to these machines from Macs due to improperly implemented Java sysex handling.  It'd be very simple to implement.

Sean

**Comment by eclab** [comment]
> (Also, your example seems to be missing the code which actually tries to send the array of `SysexMessage` objects. Does it just loop over them calling `send()`?)

That's right.  You just send each of them in turn.

**Comment by brunchboy** [comment]
OK, this is sounding different than what I thought I read in the JavaDoc you linked (as well as your example above). That seemed to imply that Java MIDI would batch up the SysEx data and send it all as a single message. But in fact you want something different? Separate messages sent at separate times? That would be easier to implement, although there would be no way to make it thread safe.

**Comment by brunchboy** [comment]
So what do you actually expect to see in MIDI monitor when you send those messages? Or does MIDI Monitor group them up if they come within a certain time period?

**Comment by brunchboy** [comment]
…although, without batching it there may simply be no way to send the message. I don’t know if the underlying CoreMIDI API supports sending a partial SysEx message.

**Comment by eclab** [comment]
> I have seen this behaviour on Java MIDI in reverse, so am I used to handling it on incoming messages on some interfaces, but never have used it on outgoing messages. I can only assume it is a legacy feature to support sending of large sysex messages over interfaces where the data buffers are smaller. I.e. you have a message that 10,000 bytes to send, but your interface only have buffers of 1,000 bytes, then you need to split the message up that fits within some intermediate buffer and then you allow a small delay before sending the next to allow the receiving device time to process the message

Correct.  A great many older synths require this, often explicitly.


> I do this in my own librarian software as I had this problem when I switched to a MOTU MIDEXPRESS 128 in 2006 which possibly has small buffers as a multi-port device, and I found that sending large messages in one go would not get received correctly. However, I simply chunk the message up, send each chunk with a delay in between each send. I do not add the F7 at the start of a buffer as you describe, and this all goes fine via CoreMIDI4J.

I am doing a similar hack right now as well.  But it's not a valid part of the Java MIDI API.  In fact it doesn't work properly in Windows.  I was chunking up sysex messages with a special MIDIMessage subclass I made, and discovered that if your last chunk happens to contain the 0xF7 at the end of the message all by itself, then Java MIDI for Windows dies hard if you submit a bare 0xF7.   I submitted a bug report and the response was: "there's a proper and documented way to do this, and you're not doing it."

And they're right.

Manual chunking is not part of the Java MIDI API, and is not guaranteed to work, whereas Java has a *specific* required solution which CoreMIDI4Java isn't implementing.  Plus it's easy!  Just look for messages starting with 0xF7 and strip it off.

**Comment by brunchboy** [comment]
Derek, I have done some experimentation with Java MIDI, and it will not let you construct a `SysexMessage` instance that starts with anything other than `f0` or `f7`. So how were you sending buffers without leading `f7` values? Or were you using something other than Java?

**Comment by eclab** [comment]
> OK, this is sounding different than what I thought I read in the JavaDoc you linked (as well as your example above). That seemed to imply that Java MIDI would batch up the SysEx data and send it all as a single message. 

No, the intent is to send them asynchronously as a stream.  So it's easy: if a SysexMessage starts with 0xF0, you send it on regardless of whether or not it ends in 0xF7.  If it starts with 0xF7, you strip off the 0xF7 and send it on.  And that's about all there's to it I believe.

> So what do you actually expect to see in MIDI monitor when you send those messages? Or does MIDI Monitor group them up if they come within a certain time period?

MIDI Monitor is being helpful in grouping them.  But that's just because it's waiting for a terminating 0xF7.  The data is actually being sent out piecemeal.

**Comment by brunchboy** [comment]
So the question then is does CoreMidi allow this?

**Comment by eclab** [comment]
> So the question then is does CoreMidi allow this?

I know that CoreMIDI allows me, as a hack, to make my own subclass of MidiMessage which I can load with arbitrary data.  This lets me send data out piecemeal on the Mac (and it works on Windows modulo the 0xF7 bug).  So I can't think of any reason why the same wouldn't work for Sysex messages.

**Comment by brunchboy** [comment]
By “allow” I mean without hacks. 😄 

It is also confusing to me where these `f7` values in later packets are coming from, because we are asking Java for the data contents of the `SysexMessage` packets, which my experimentation has proven, does _not_ include the leading `f7` pseudo-status for continuation objects: https://github.com/DerekCook/CoreMidi4J/blob/68e56e8771b90b30aea66569b910d0bb3b979401/CoreMIDI4J/Native/CoreMidi4J/CoreMidiOutputPort.cpp#L117-L119

Ah. I think I know what is more likely going on: It is not those bytes that are the problem. I bet CoreMidi is always putting an `f7` at the end of the SysEx message for us, even if we are not asking it to. So we need to find some supported CoreMIDI API for sending an incomplete SysEx message.

**Comment by brunchboy** [comment]
Anyway, I agree this is a real issue that would be nice to resolve. To start with we should probably immediately throw exceptions when you try to send partial SysEx messages because we can’t yet support them. @eclab if you can come up with a clean way to support them, a pull request will be most welcome. In the mean time I will continue pondering and researching as a background task. Thanks again for reporting this!

**Comment by brunchboy** [comment]
I’ve poked at this a bit more, and have some good and some bad news.

First, the good. I was misinterpreting the above code, thinking it was calling the [getData](https://docs.oracle.com/en/java/javase/14/docs/api/java.desktop/javax/sound/midi/SysexMessage.html#getData()) method on the [SysexMessage](https://docs.oracle.com/en/java/javase/14/docs/api/java.desktop/javax/sound/midi/SysexMessage.html) class, which does strip off the status byte. However, it’s not doing that at all, it is accessing the protected [data](https://docs.oracle.com/en/java/javase/14/docs/api/java.desktop/javax/sound/midi/MidiMessage.html#data) array of the parent [MidiMessage](https://docs.oracle.com/en/java/javase/14/docs/api/java.desktop/javax/sound/midi/MidiMessage.html) class, which _does_ include the status bytes. So that would allow us to detect and remove the leading `f7` bytes in SysEx continuation messages (at the C++ level).

Now, the bad. When we tell CoreMIDI to send a partial SysEx message using the existing code (in other words, we omit the trailing `f7` byte in the data array), CoreMIDI “helpfully” adds one for us. So the API we are using is simply not able to support split SysEx messages. We will need to find and use an alternate API.

Also, the CoreMIDI functions we are using, like [MIDIPacketListAdd](https://developer.apple.com/documentation/coremidi/1495128-midipacketlistadd?language=occ) and [MIDISend](https://developer.apple.com/documentation/coremidi/1495289-midisend?language=occ) are all deprecated! And the deprecation warnings do not provide any useful information about what you are supposed to use instead. It took a frustratingly long time for me to find an [answer](https://developer.apple.com/forums/thread/652427). But I am not confident that even switching to these new APIs will necessarily fix things; the documentation for [MIDIEventPacket](https://developer.apple.com/documentation/coremidi/midieventpacket?language=objc) says that it supports partial system-exclusive messages, but so does the documentation for the (deprecated) [MIDIPacket](https://developer.apple.com/documentation/coremidi/midipacket?language=occ) that we are using today.

So, a couple of hypotheses here…

One possibility is that we need to send all the packets of the fragmented SysEx message to CoreMIDI at the same time, so that it can study them and make sure they are properly formed as a batch, with the final packet containing the trailing `f7` byte, to stop it adding extra `f7` bytes to the ends of the other packets the way it is now. But that would defeat the purpose of sending them slowly for old hardware, unless we could use the timestamp mechanism to schedule individual packets further and further into the future. But CoreMIDI may disallow that, due to worry about other packets being sent in the middle, which would lead to a mal-formed MIDI stream.

Alternately, for handling fragmented SysEx messages, we may need to instead use the more focused API [MIDISendSysex](https://developer.apple.com/documentation/coremidi/1495356-midisendsysex?language=objc) whose argument [MIDISysexSendRequest](https://developer.apple.com/documentation/coremidi/midisysexsendrequest?language=objc) contains a `complete` flag to explicitly tell CoreMIDI that it is a partial message.

But this is all very poorly documented, and I couldn’t even find any promising-looking books that would help. We might need to open a developer support request for this.

In any case, this all lives in the C++ side of things, and so I am going to have to leave it in Derek’s court, as he is the C++ developer. I propose we add code to throw exceptions when you try to send a partial SysEx message, and hope that in some future release Derek might be able to find a way to make it work. It’s going to take a lot of research and experimentation though.

**Comment by eclab** [comment]
On the Mac, using CoreMidi4J, I can create a Java subclass called DividedSysex...

    public static class DividedSysex extends MidiMessage
        {
        public byte[] getData() { return data; }
        public Object clone() { return new DividedSysex(getMessage()); }
        public DividedSysex(byte[] data) { super(data.clone()); }
        public int getStatus() { return 0xF0; } // not that this really matters 
	}

And then I can say...

         DividedSysex d1 = new DividedSysex(new byte[] { (byte)0xF0, 1, 2, 3, 4});
        // then send d1
        // then pause for a while
         DividedSysex d2 = new DividedSysex(new byte[] {  5, 6, 7, 8, 9 });
        // then send d2
        // then pause for a while
         DividedSysex d3 = new DividedSysex(new byte[] {  10, 11, 12, 13, (byte)0xF7 });
        // then send d3

... and this hack works fine.  The messages have pauses, and are ultimately considered to be one large sysex message.  

Why would this be able to get through CoreMIDI, but a similar message from a series of stripped Sysex messages would not?

**Comment by brunchboy** [comment]
That is an excellent question, and a promising sign. I plan to do more testing, instrumenting the C++ and so on. Could you please post your full test classes, both the original one that does not work, and this new one, so I can base things off them? I do not have any pure Java MIDI code to work with, I only use Clojure these days, and the more variables I can eliminate, the better.

**Comment by brunchboy** [comment]
(In particular, the code I need to steal is the part that sets up the MIDI device, and then uses it to send the messages.)

**Comment by brunchboy** [comment]
Also, what version of macOS are you using? I was testing with Catalina this afternoon, which may make a difference.

**Comment by brunchboy** [comment]
Ah ha! I figured out something else important. I was able to extract the raw Java classes from the Clojure wrappers I was using and poke at them a bit more, and I was definitely seeing CoreMIDI adding the missing trailing `f7`. But I discovered if I sent the next packet soon enough, it would not! If I send a partial SysEx packet and follow it up with another packet in less than one second, CoreMIDI does _not_ add an extra `f7` after the first packet. If I take more than 1000ms between packets it does. How long were you waiting between packets, @eclab?

I think I have enough information now to try building an experimental build which solves this problem.

**Comment by brunchboy** [comment]
Woo hoo! 🎉 I have deployed a snapshot version, `1.5-SNAPSHOT` to Maven Central which fixes this for me, whether I am using my Clojure wrapper, or dropping down to the low-level Java classes. As long as I send the continuation packets at an interval of less than a second, they show up as a single SysEx message without any extraneous `f7` characters until the one that belongs at the end of the message. Thanks so much for finding and explaining this, @eclab, I have credited you in the release note. Could you give it a try and let us know if it works for you as well? If you don’t use Maven, my continuous integration script on GitLab has also made a jar available at https://github.com/DerekCook/CoreMidi4J/releases/tag/V1.5-SNAPSHOT

If this works for you, then as soon as Derek is comfortable with his own testing of it, we can make another official release (unless there’s something else you’ve been wanting to get around to first, @DerekCook).

**Comment by brunchboy** [comment]
Just to be clear, Derek, this change will not require you to change the way you are currently sending long SysEx messages. Evidently CoreMIDI handles that, stripping off the extra `f0` characters you’ve been using at the start of packets after the first, until one ends with `f7`. Which is nice of it. But it will allow cross-platform code which follows Java’s officially-supported way of doing this to work properly as well, so you could switch to that if you liked.

It was interesting discovering that CoreMIDI _does_ implement a timeout like I was speculating about in my first response! It forces a hanging SysEx message to end after one second of inactivity.

If anyone was wondering about why there was such a long pause between the SysEx fragments I was sending that I encountered this behavior, it’s because I was sending them manually, evaluating expressions at the Clojure REPL to construct and send the `SysexMessage` objects. So even though Emacs sped things up by letting me use command-line recall and structural editing to build the expression that constructed and sent the second segment, it took well over a second between them. It wasn’t until I started using compound expressions which sent multiple messages, interspersed with `Thread.sleep()` to explicitly control the timing, that I was able to see split SysEx working the way it should.

**Comment by eclab** [comment]
Initial tests suggests it might be working. 

For you to do a more extensive (but very easy to set up) test, I have made a special version of the edisyn source code here.

http://robo1.cs.gmu.edu/edisynsrc.tar.gz

In edisynsrc/jar you'll find edisyn.jar.  It contains the V1.5 snapshot cm code.You can run it as

    java -jar edisyn.jar

Next, you'll be presented with a window that says "Select a synthesizer to edit".  Under "Recent" select "Select another synthesizer...".  Then under "All Synths", select "Yamaha FB-01" (do NOT select "Yamaha FB-01 [Multi]".  Then press "Open".

You'll see a patch editor panel and be presented with a MIDI Devices window.  Select your outgoing MIDI device in the "Send To" panel.  The other stuff doesn't matter so much.  Click Okay.

Under the menu, select File->Load..., then choose a Yamaha FB-01 Bank Sysex .syx file from the directory edisynsrc/fb01/ 

The FB01 bank sysex files have two bank sysex each.  You'll be uploading one of them.  When you wee the "Bank Sysex Received" window, click on "Write Bank".  When it says "Write the whole bank to the synth?", pick Bank 1(A) if you're given a choice, and press "Okay".

Edisyn now uploads the entire bank sysex message to the synth.  On the FS1R the bank must be interspersed with pauses.  Edisyn does this by breaking it up into sysex messages as described.  It prints them all to the terminal window.  The first one will look something like this:

    SM[ 0xF0 0x43 0x75 0x 0 0x 0 0x 0 0x 0 0x 0 0x40 
    0x 7 0x 3 0x 0 0x 2 0x 0 0x 2 0x 0 0x 2 0x 0 0x 2 
    0x 0 0x 2 0x 0 0x 2 0x 0 0x 2 0x 0 0x 0 0x 0 0x 0 
    0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 
    0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 
    0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 
    0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 
    0x 0 0x 0 0x 0 0x 0 0x68]

Subsequent messages may look like this:

    SM[ 0xF7 0x 1 0x 0 0x 0 0x 5 0x 5 0x 4 0x 1 0x 4 
    0x 6 0x 5 0x 9 0x 5 0x 0 0x 2 0x 0 0x 2 0x 0 0x 0 
    0x 8 0x C 0x 0 0x 8 0x C 0x 0 0x 8 0x 7 0x 9 0x 3 
    0x 0 0x 6 0x 0 0x 4 0x 8 0x E 0x B 0x 3 0x 0 0x 0 
    0x 0 0x 0 0x 2 0x 1 0x F 0x 1 0x 7 0x 0 0x 0 0x 0 
    0x 7 0x 1 0x 4 0x 2 0x 0 0x 0 0x 0 0x 0 0x F 0x 0 
    0x F 0x 5 0x 5 0x 1 0x 0 0x D 0x D 0x 8 0x C 0x 0 
    0x 0 0x 0 0x 0 0x 5 0x 1 0x 0 0x 4 0x D 0x B 0x 0 
    0x 6 0x 0 0x 6 0x 0 0x 0 0x 0 0x 0 0x 1 0x 0 0x 0 
    0x 1 0x 0 0x 3 0x D 0x A 0x 0 0x 1 0x 0 0x 6 0x 0 
    0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 
    0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 
    0x 0 0x 0 0x 2 0x 2 0x 0 0x 0 0x 0 0x 0 0x 0 0x 0 
    0x 0 0x 0]

Sorry for the spaces after each x.

Note that the first message properly starts with 0xF0, later messages start with 0xF7, and the final message also ends with 0xF7.

Finally, examine what happens when this message transmit is read by MIDI Monitor.

You can change the coremidi4 jar file by replacing the file in edisynsrc/libraries/

Then just do

    make jar

... and your rebuilt edisyn.jar file will be in the edisynsrc/jar directory.

RESULTS:

ORIGINAL coremidi4j: MIDI Monitor displays one short sysex messages, followed by multiple invalid ones.  The short sysex message starts with 0xF0 and ends with 0xF7 (clearly taken from the next message.  The next message has no starting status byte.  Subsequent messages start with 0XF7.  The final message starts and ends with 0xF7.  Basically it's the same pattern as I had described in the initial message.

NEW coremidi4j: MIDI Monitor waits until the whole message is transferred and displays it as a single sysex message.

WHAT I DO NOT KNOW:

I currently have no synthesizer which requires pauses, meaning that I cannot at present test to see if the messages are being sent with pauses or if coremidi is buffering them all up and then sending them out together.  I think it is likely working properly, but I don't know for sure.

**Comment by brunchboy** [comment]
I can confirm that split SysEx messages are being sent as they are presented to CoreMIDI. I could see that happen in MIDI monitor: the first chunk would arrive, MIDI Monitor would display a spinner to show it was an incomplete SysEx message, and then once the final segment arrived, it would be displayed in full. (This is when I was testing different delays between segments.)

**Comment by DerekCook** [comment]
That was fast James! I won't be able to do any testing until the weekend at the earliest, as work is nuts at the moment.

**Comment by brunchboy** [comment]
No rush at all, I am eager to hear if it works for ECLab though. 😄

**Comment by brunchboy** [comment]
@eclab do you think you will be able to test the snapshot build?

**Comment by brunchboy** [comment]
Whoops, I misread this and hadn’t noticed ECLab reporting that it seemed to work! So as soon as Derek is happy, we can move forward. (Not trying to put pressure on you, Derek, just correcting the record for our future selves.)

**Comment by DerekCook** [comment]
Sorry, work has been a complete nightmare for the past two weeks with no free time at all. But come what may I am having this weekend off, so hopefully will get to check this then (and turn the keyboards on for the first time in weeks!

**Comment by brunchboy** [comment]
Sorry to hear that! But I sincerely am not trying to nudge you to do this, so if you need the entire weekend to just wander around outside and rest, by all means take it for that! 😄

**Comment by DerekCook** [comment]
Hi, James

I know that, so no worries at all. I was just explaining my radio silence. I will get around to it, sadly work has taken over again today, but hopefully in the next few days I will get my AN1x setup to check things initially.

**Comment by DerekCook** [comment]
Hi. 

I finally have a weekend free of work, so had some time to check this out. It certainly is working fine with my AN1x (the easiest synth to pull out of my keyboard room to being beside my Mac!

I've done SYSEX transfers in both directions, and it all seems fine

**Comment by DerekCook** [comment]
> Derek, I have done some experimentation with Java MIDI, and it will not let you construct a `SysexMessage` instance that starts with anything other than `f0` or `f7`. So how were you sending buffers without leading `f7` values? Or were you using something other than Java?

Hi, James

Just to provide an answer to this question, I guess it is working, because I have a constructor that allows me to do that, which is not calling a super constructor, so I can set the message payload to anything I want. I cannot remember if I ran into the problem you are talking about and deliberately wrote the constructor this way, as this was all written about 17 years ago. 

I've watched this in the debugger and checked that there is no F7 at the start of the message before goes into the receiver's `send()` function


This is the constructor 

`	public SynthSysexMessage(byte[] message) {
		
		super.data = (byte[]) message.clone();
		super.length = data.length;
		
	}
	
`

And I use this as follows inside my own transmit function

`public void transmit(SynthMidiOutputPort output) throws MidiUnavailableException {
		
		int bufferSize = SynthMidiSystem.getPrimaryBufferSize();
		int bufferDelay = SynthMidiSystem.getPrimaryBufferDelay();

		if ( super.data.length > bufferSize) {

			int numberOfMessages = ( super.data.length / bufferSize ) + 1;
			int offset = 0;
			int length = 0;

			for ( int i = 0; i < numberOfMessages; i += 1 ) {

				ByteArrayOutputStream stream = new ByteArrayOutputStream();

				if ( i == ( numberOfMessages - 1) ) {

					// The final buffer size is the length of the main message minus the offset position we
					// have reached whilst writing the other messages
					length = super.data.length - offset;

				} else {

					length = bufferSize;

				}

				stream.write(super.data, offset, length);

				offset += length;

				SynthSysexMessage message = new SynthSysexMessage(stream.toByteArray());

				output.transmitMessage(message);

				SynthMidiSystem.delay(bufferDelay);

			}

		} else {

			output.transmitMessage(this);

		}
		
    if ( SynthProperties.enableMidiLogging ) {
      
      ApplicationLogger.writeDebugMessage("  -- Using Port: " + output.getPortName());
      SynthMidiSystem.logMidiMessage("  -- Transmitting " + this.getLength() + " bytes", this);    
      
    }

}
`

**Comment by brunchboy** [comment]
Ah, so you were using your own subclass of `SysexMessage` which skipped this enforcement, that makes sense. I was trying to use just the vanilla one that comes with the JDK, and it would not let me.

In any case, it looks like we are ready to cut a new release then, right?

**Comment by eclab** [comment]
That's my hack too.  But it has problems on Windows.

**Comment by DerekCook** [comment]
Strange as I have never seen a problem on Windows with this approach (and it was developed on Windows until I switched to a Mac in 2012), nor have anybody ever reported anything that I have traced to this. 99% of MIDI problems reported to me from uses are those ones using the really cheap USB MIDI leads.  

Jim, yes, I think we can go for a release.

**Comment by eclab** [comment]
I've triggered crashing bugs on Windows (which I've reported) using this approach.  The response has been: well, you shouldn't be doing it that way, use the standard Sysex class.  And they're right.

**Comment by DerekCook** [comment]
Ah, OK. Never had that problem myself to my knowledge across my own development hours and my users.

**Comment by brunchboy** [comment]
Version 1.5, which fixes this and one other issue, has now been released and published to Maven Central. Thanks!

**Comment by eclab** [comment]
> Ah, OK. Never had that problem myself to my knowledge across my own development hours and my users.

BTW, the fun one is sending a bare 0xF7 as a single customized message.  That one crashes the program hard in Windows.
