### ISSUE TITLE
IllegalArgumentException when using addNotificationListener on Windows and Linux

### ISSUE THREAD

**Issue by mailuefterl-sro** [DerekCook/CoreMidi4J#38]
On Windows and Linux machines, MidiSystem.getMidiDevice *sometimes* throws an IllegalArgumentException, but only if addNotificationListener has been used before.

**Comment by brunchboy** [comment]
Thanks for reporting this. In order to address it, we will need a stack trace, and a small, self-contained way to replicate it.

**Comment by brunchboy** [comment]
Actually, what does this have to do with CoreMIDI4J? `MidiSystem` is a built in Java class. Which class are you calling `addNotificationListener` on?

**Comment by mailuefterl-sro** [comment]
(sorry misclicked submit button too early...)
The problem seems to be that there is a background thread submitting getMidiDeviceInfo() periodically, and this seems to generate new Info objects with new uniqueIds, rendering the old objects invalid.
The supplied example program sometimes works correctly, sometimes (~10%) gets InvalidArgumentExceptions like in the supplied example output.

[miditest.zip](https://github.com/DerekCook/CoreMidi4J/files/5366634/miditest.zip)

**Comment by brunchboy** [comment]
Thanks for the clarification, that helps. In general, in situations like this, you should output the entire stack trace, not just the exception. As neither Derek or I use Windows or Linux regularly, I’m not sure when we will be able to investigate this. If you can get further and submit a pull request to fix the problem that would be wonderful!

**Comment by brunchboy** [comment]
You are correct that on non-Mac platforms, calling `addNotificationListener()` on `CoreMidiDeviceProvider` will start a background thread to notify you of changes to the MIDI environment. It sounds as though perhaps when such changes occur, device IDs change? It would seem to be a broken API to me if simply enumerating devices would break the device IDs used by a different thread, though.

**Comment by mailuefterl-sro** [comment]
I have tried to find the difference between runs that work OK and runs that throw the IllegalArgumentExceptions.
The attached Infotest.java calls MidiSystem.getMidiDeviceInfo two times, then tries to get the MidiDevice from the first Info object and compares the two instances of the corresponding Info objects. When calling CoreMidiDeviceProvider.addNotificationListener() before calling MidiSystem.getMidiDeviceInfo() for the first time, getDevice will fail most of the time. And I saw that when it fails, the corresponding Info objects have the same content but different hashCode (i.e. they have been newly instantiated).
When no notificationListener was added, it succeeded 100% of the time, and the Info objects were identical. It almost drove me crazy.
Then I instrumented the MidiSystem class with some debug printfs, and found out that the MidiSystem.getMidiDeviceInfo calls from two threads (main and CoreMidi4J environment change scanner) were overlapping, and returned different Info objects for the same device. Later calls to getMidiDeviceInfo returned consistent Info objects with a constant hashCode. When trying to call getDevice() with a stale Info object (i.e. one with hashCode != the latest one) would not find the device and throw the IllegalArgumentException.
So the culprit seems to be that two threads are calling MidiSystem.getMidiDeviceInfo at the same time and building two versions of the device caches. I could also verify this later with a background thread that was repeatedly calling getMidiDeviceInfo() while the main thread was also doing it for the first time, even when CoreMidi4J was not involved at all.
One easy fix is to ensure that getMidiDeviceInfo() is called and completed before a second thread can interfere. I moved the first call to snapshotCurrentEnvironment out of the background thread into addNotificationListener before the thread is created, and was not able to reproduce the problem again. Will send a pull request for it.
But the same might happen later, when midi devices are added. So it might be a good idea to also synchronize CoreMidiDeviceProvider.getMidiDeviceInfo() to snapshotCurrentEnvironment.

[infotest.zip](https://github.com/DerekCook/CoreMidi4J/files/5370560/infotest.zip)
contents:
- Infotest.java test program
- MidiSystem.java.excerpt instrumented getMidiDeviceInfo method (from jdk1.8, later versions are very similar and show the same problem)
- out_notify.txt test program output when the problem arises
- out_no_notify.txt output when addNotifyListener() was commented out, problem does not appear
- out_background.txt output without notifyListener, but with background thread calling getMidiDeviceInfo: Problem arises
- out_fixed.txt output with modified CoreMidiDeviceProvider and addNotifyListener enabled (no problem).

**Comment by brunchboy** [comment]
Wow, very interesting. Thanks for all this investigation, and the fix so far. I agree this probably needs more in the long run. Perhaps this should be fixed at the level of the JDK?

**Comment by brunchboy** [comment]
(That’s mostly a joke, as there would be no need for CoreMidi4J to exist if they would fix MIDI problems at the level of the JDK. I’ll study your PR and think about what we’d need to do to fix the other race condition as well, while being wary of deadlock, when I have some time.)

**Comment by brunchboy** [comment]
Thanks again for the PR, I finally had some time to study it, and I don’t think we have arrived yet at a good solution for this. If `getMidiDeviceInfo()` cannot safely be called by multiple threads, there is nothing we can do inside CoreMIDI4J to protect against that happening except for offering our own synchronized wrapper around that method, and mandating that any code that wants to use our MIDI change notification must only use our synchronized wrapper, never calling `getMidiDeviceInfo()` directly.

That might work, but only if people properly understand and implement it. Another approach would be to simply remove our attempt to offer MIDI environment change detection on non-Mac platforms, since the JDK does not seem to offer a safe way of supporting it. I am personally leaning towards the latter choice, but wonder what you and Derek think.

**Comment by brunchboy** [comment]
While we consider our options here, I think I will go ahead and cut a new release containing the fix for split SysEx messages, in any case. But I will cook and eat dinner first in case anyone thinks I should wait until this issue is resolved as well.

**Comment by brunchboy** [comment]
@mailuefterl-sro it sounds as though, as long as two threads are not calling `MidiSystem.getMidiDeviceInfo()` at the same time, things work correctly, even if the method is called multiple times. Is that your experience? Based on that understanding, I have just pushed a new snapshot version which adds synchronization around our use of that function, and which warns users of our library to never call `MidiSystem.getMidiDeviceInfo()` directly if they also want to use `CoreMidiDeviceProvider.addNotificationListener()`. Could you see if the latest build of version 1.5-SNAPSHOT solves the problem for you, as long as you avoid calling `MidiSystem.getMidiDeviceInfo()` and instead call `CoreMidiDeviceProvider.getMidiDeviceInfo()`?

If that works for you, I would like to include this fix as part of the 1.5 release. If it does not work for you, then I think we just need to stop supporting `addNotificationListener()` on non-Mac systems, because not even synchronizing access to this method is enough.

**Comment by DerekCook** [comment]
I don't actually use the notification function myself in my software, but what James has proposed so far all sounds sensible.

**Comment by mailuefterl-sro** [comment]
Yes, the change looks fine and I have not been able to reproduce the issue with this fix applied on Linux or Windows. Thanks!

**Comment by brunchboy** [comment]
Great! Somehow I missed seeing your response until now, but I will cut the new release tonight. Thanks again for reporting this and testing the fix.

**Comment by brunchboy** [comment]
All right, version 1.5 is released and published to Maven Central! 😄
