### ISSUE TITLE
The list of devices available will not correctly update if you connect devices after Java is already running

### ISSUE THREAD

**Issue by Mfactory4444** [DerekCook/CoreMidi4J#47]
Hello,
When i copy paste the example provide, but add to the void watchForMidiChanges() the following code:

     System.out.println("Updated Working MIDI Devices:");
        for (javax.sound.midi.MidiDevice.Info device : CoreMidiDeviceProvider.getMidiDeviceInfo()) {
            System.out.println("  " + device);
        }

I am expecting to see, when I plug a new device, this device appearing in the list (with the CoreMidi4J' implementation)
But, this is not happening; the watchForMidi change listener is indeed called when the device is plugged, but it does not appear in the list. If the device is plugged from the beginning, it is appearing properly; it it is removed, it indeed disappear from the list; but it doesn't appear back if plugged after the program start.

**Comment by brunchboy** [comment]
Hello! I would expect to see what you expect to see, and indeed, that is the way it works for me. What operating system and Java version and version of CoreMidi4J are you using?

**Comment by Mfactory4444** [comment]
Hello, Thanks for your quick reply. I am using CoreMIDI4J version 1.6, and running on Mac OS Ventura (13.0) on a Macbook Air M2 (ARM)
I have found also than if I start the program with let's say 2 MIDI devices connected, both of them are listed with CoreMIDI4J implementation; but if I unplug one of those, then the watchForMIDIchange listener, augmented with the code to print the list of connected devices, will no longer show any CoreMIDI4J devices (including the one that I haven't unplugged)!
If I use the Java method MidiSystem.getMidiDeviceInfo(), I have the same behaviour: the CoreMIDI4J version of the devices appear in there, until I unplug anyone of the devices; then no more CoreMIDI4J versions of any device is accessible, including the device I haven't touched.
I tried to see if, after a device in unplugged, the library is still loaded, the result is yes.

**Comment by brunchboy** [comment]
I am not able to reproduce this problem on my M2 MacBook Pro running macOS Ventura 13.6.2. My first suggestion would be to update to a current build of the OS and try again. If that still doesn’t work for you, you may need to build a version of the project with additional debugging lines, and see if you can figure out what is strange happening on your system.

**Comment by Mfactory4444** [comment]
Hello, I updated to Mac OS Sonoma 14.1.1, and the problem is still there. What kind of additional debug lines would you suggest to add? I have built a jar using the example code provided, and just added the following code to the watchForMIDI change until now

 System.out.println("Updated Working MIDI Devices:");
    for (javax.sound.midi.MidiDevice.Info device : CoreMidiDeviceProvider.getMidiDeviceInfo()) {
        System.out.println("  " + device);
    }

**Comment by Mfactory4444** [comment]
Hello, I precise also that I am using the coremidi4j-1.6.jar as an external dependency (described as 'standalone' in the explanation provided). I am using Eclipse and I don't now how to embed it as described (maven central method). I am not a professional developper, I dont know if using the standalone jar makes a difference or not. Also, I am using JDK 17, I dont know if this is hogher than the 1.7 version recommanded
![coremidi](https://github.com/DerekCook/CoreMidi4J/assets/40041061/cb18e378-b0f8-4131-9f6d-2397e807f237)
![jdk17](https://github.com/DerekCook/CoreMidi4J/assets/40041061/95a30b30-0c4c-40f8-9ee2-8231952e5f67)

**Comment by brunchboy** [comment]
Ah, I meant that you should try updating to the latest version of Ventura (you had said you were at 13.0, and the latest is 13.6.2). I don’t know when I will be able to update to Sonoma myself, because some of my audio software is not yet compatible with it. However, I think the most likely issue is perhaps your Java version. Java 1.7 would be called Java 7 under today’s versioning scheme, so it is _much_ older than Java 17. I was testing under Java 11. I will try to find some time to test under Java 17, but unfortunately I can’t predict when that will be. My mother is in hospital five hundred miles away, and I have several other urgent issues competing for my time. I can’t speak for Derek, but I know he is also often very busy. I also can’t try to help you with detailed exploratory guides remotely. If you need this resolved quickly, the first thing to try would be running under Java 11, which was known to work. The second thing would be to find and hire a professional developer who is skilled in Java and Objective C to work with you.

Also note that the Java environment you are using to run the code is not necessarily the same as the Java version to which you are compiling, which is what you showed in the screen shot. You can tell what version is running on the system overall by typing `java --version` in a terminal. You will have to consult your IDE’s manual to determine how to choose the runtime version when you are running from within it (I haven’t used Eclipse since roughly 2002). But you will need to compile to a version that is less than or equal to the version you want to run with, so for now I would compile to version 11 and run in version 11.

Running standalone should work fine; you don’t need to worry about embedding it unless you are trying to build a convenient single-file package for other users.

**Comment by brunchboy** [comment]
Well, I was able to steal a few minutes to try under Amazon Corretto Java 17.0.1, and it still worked fine for me, so I don’t think the Java version is necessarily the issue either. At this point your best bet is going to be finding a skilled Java and Objective C colleague to work with, I am afraid, because I can’t imagine what is happening on your system. Are there any errors logged anywhere?

And since I always use the embedded approach, I will try to find some time next to test standalone mode, just in case that is a factor. But again, sorry, I can’t predict when that might be.

**Comment by brunchboy** [comment]
All right, I stole a few more minutes and tried reproducing exactly what you described, and it is all working just fine for me, with the modified `Example.java` and running the downloaded CoreMIDI4J version 1.6, as a standalone jar, under Java 17. Just to be sure you put your added code in the right place, here is the entire modified `Example.java` source:

```java
import uk.co.xfactorylibrarians.coremidi4j.CoreMidiDeviceProvider;
import uk.co.xfactorylibrarians.coremidi4j.CoreMidiNotification;
import uk.co.xfactorylibrarians.coremidi4j.CoreMidiException;
import javax.sound.midi.MidiDevice;

public class Example {

    public static boolean isCoreMidiLoaded() throws CoreMidiException {
        return CoreMidiDeviceProvider.isLibraryLoaded();
    }

    public static void watchForMidiChanges() throws CoreMidiException {
        CoreMidiDeviceProvider.addNotificationListener(new CoreMidiNotification() {
                public void midiSystemUpdated() {
                    System.out.println("The MIDI environment has changed.");
                    System.out.println("Updated Working MIDI Devices:");
                    for (javax.sound.midi.MidiDevice.Info device : CoreMidiDeviceProvider.getMidiDeviceInfo()) {
                        System.out.println("  " + device);
                    }
                }
            });
    }

    public static void main(String[] args) throws Exception {
        System.out.println("Working MIDI Devices:");
        for (javax.sound.midi.MidiDevice.Info device : CoreMidiDeviceProvider.getMidiDeviceInfo()) {
            System.out.println("  " + device);
        }

        if (Example.isCoreMidiLoaded()) {
            System.out.println("CoreMIDI4J native library is running.");
        } else {
            System.out.println("CoreMIDI4J native library is not available.");
        }

        watchForMidiChanges();
        System.out.println("Watching for MIDI environment changes for thirty seconds.");
        Thread.sleep(30000);
    }
}
```

And I compiled it like this (your path to the jar will vary, of course):

    javac -cp ~/Downloads/coremidi4j-1.6.jar Example.java

And ran it like this:

    java -cp ~/Downloads/coremidi4j-1.6.jar:. Example

And I see MIDI devices coming and going just fine:

````
Working MIDI Devices:
  CoreMIDI4J - IAC Driver Bus 1
  CoreMIDI4J - IAC Driver Bus 2
  CoreMIDI4J - nanoKONTROL2
  CoreMIDI4J - IAC Driver Bus 1
  CoreMIDI4J - IAC Driver Bus 2
  CoreMIDI4J - nanoKONTROL2
  Gervill
  Real Time Sequencer
CoreMIDI4J native library is running.
Watching for MIDI environment changes for thirty seconds.
The MIDI environment has changed.
Updated Working MIDI Devices:
  CoreMIDI4J - IAC Driver Bus 1
  CoreMIDI4J - IAC Driver Bus 2
  CoreMIDI4J - IAC Driver Bus 1
  CoreMIDI4J - IAC Driver Bus 2
  Gervill
  Real Time Sequencer
The MIDI environment has changed.
Updated Working MIDI Devices:
  CoreMIDI4J - IAC Driver Bus 1
  CoreMIDI4J - IAC Driver Bus 2
  CoreMIDI4J - IAC Driver Bus 1
  CoreMIDI4J - IAC Driver Bus 2
  CoreMIDI4J - nanoKONTROL2
  CoreMIDI4J - nanoKONTROL2
  Gervill
  Real Time Sequencer
The MIDI environment has changed.
Updated Working MIDI Devices:
  CoreMIDI4J - IAC Driver Bus 1
  CoreMIDI4J - IAC Driver Bus 2
  CoreMIDI4J - IAC Driver Bus 1
  CoreMIDI4J - IAC Driver Bus 2
  Gervill
  Real Time Sequencer
The MIDI environment has changed.
Updated Working MIDI Devices:
  CoreMIDI4J - IAC Driver Bus 1
  CoreMIDI4J - IAC Driver Bus 2
  CoreMIDI4J - IAC Driver Bus 1
  CoreMIDI4J - IAC Driver Bus 2
  CoreMIDI4J - nanoKONTROL2
  CoreMIDI4J - nanoKONTROL2
  Gervill
  Real Time Sequencer
````

**Comment by brunchboy** [comment]
I guess one more thing for you to consider trying is doing exactly the above at the terminal, in case it is the Eclipse IDE that is causing problems?

**Comment by brunchboy** [comment]
I just realized that we have one very important unanswered question, which is the actual Java version you are running. You showed that you were compiling for compatibility with Java 17, but that is a completely different question. Rather than trying to dive through the documentation of Eclipse to figure this out, you could add the following lines to the start of `main()`, right before the line that prints "Working MIDI Devices:"

```java
        System.out.println("Java version: " + System.getProperty("java.version"));
        System.out.println("Java VM: " + System.getProperty("java.vm.name"));
        System.out.println("Java vendor: " + System.getProperty("java.vm.vendor"));
```

Now when I run the example program, I see these initial lines of output:
```
Java version: 17.0.1
Java VM: OpenJDK 64-Bit Server VM
Java vendor: Amazon.com Inc.
Working MIDI Devices:
  CoreMIDI4J - IAC Driver Bus 1
…
```

**Comment by Mfactory4444** [comment]
Hello. WOW, thanks for this reply. First, I tried to 'properly' recompile my project with Java 11, and also to change execution environment to Java 11. Without success. Then I tried your example, compiling without Eclipse, but with Java 17. It was a success! So I made a few tests and found out that the problem was coming from Eclipse; I was packaging the CoreMIDI4J jar inside my own jar, and this was not posing any issue to use the library (CoreMIDI4J ports were available and working well), EXCEPT for the hot plug feature. Recompiling the project asking Eclipse to **copy** CoreMIDI4J **into a sub folder** next to my own jar was the solution! Now I can use hot plug feature on y project. Thanks for the help, and best wishes to your mother!! :)

**Comment by brunchboy** [comment]
Yes, if you want to have CoreMidi4J in your own jar, then you need to learn how to work with Maven and follow the embedded approach. That’s how I use it in my own projects, but Maven is a big topic to learn, so if you are happy with the way things are working now, you can avoid doing that, and you can revisit your approach to this once you are using enough Maven libraries to dive into that world.

**Comment by brunchboy** [comment]
Thanks for letting us know you got this working! 😄
