### ISSUE TITLE
JDK version <=1.6

### ISSUE THREAD

**Issue by dandaka** [DerekCook/CoreMidi4J#7]
### Right now

When user launches CoreMidi4J with Java 1.6, they get:
- No errors from CoreMidi4J
- Broken MIDI functionality
### Could be
1. User has old version of Java
2. CoreMidi4J is not replacing standard Java MIDI
3. Says to user in log/console, that it can't be used

**Comment by brunchboy** [comment]
We’ve been discussing this a bit in email, and it may be difficult to achieve because of the way Java deals with classes compiled for different versions. We will see if we can do it, but in the mean time will be clear in our installation instructions that you need at least Java 1.7.

**Comment by DerekCook** [comment]
CodeMIDI4J is compiled as a JRE 1.7 JAR file as in its current form it is derived from a code base that used JRE 1.7 specific features in the Javax MIDI classes. 

Do you have a specific reason to remain with 1.6? It is now a very old version of Java, no longer supported by Apple. Indeed 1.7 will probably be end of life soon.

My whole journey with CoreMIDI4J started because I wanted to move onto later versions (some users were complaining about being stuck with 1.6) and MMJ not working on the later versions!

**Comment by dandaka** [comment]
No, I don't have any specific reasons to stay with 1.6. I think it was a default version with my OSX and I had no reasons to upgrade.

**Comment by DerekCook** [comment]
OK. I've added a note to the release notes that this is for 1.7 and above (I already say that on the project page). I understand from James that you have now installed a later version of Java. I'll close this issue. Please feel free to raise any issues you find when testing against the later versions.
